title: Alicia Fortes Machado
logo: /assets/img/me.jpg
description: Evolving website about interests and information about myself.
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme